version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: coffeeapp-mysql
    environment:
      MYSQL_ROOT_PASSWORD: "0000"
      MYSQL_DATABASE: CoffeeAppMiahkykh
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql


  springboot-app:
    build:
      context: .
    image: coffeeapp-miahkykh:latest
    container_name: coffeeapp
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/CoffeeAppMiahkykh?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: "0000"
    volumes:
      - ./logs:/app/logs
      - ./uploads:/app/uploads

volumes:
  mysql_data:
