version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: coffeeapp-miahkykh-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 0000
      MYSQL_DATABASE: CoffeeAppMiahkykh
    ports:
      - "3310:3306"
    networks:
      - coffeestore-miahkykh

  coffeeapp:
    image: glyuchnoglaz21/coffeeapp-miahkykh:latest
    container_name: coffeeapp-miahkykh
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://coffeeapp-miahkykh-mysql:3306/CoffeeAppMiahkykh?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 0000
    depends_on:
      - mysql
    networks:
      - coffeestore-miahkykh

networks:
  coffeestore-miahkykh:
    driver: bridge
