#server:
#  port: 8081
#  servlet:
#    session:
#      timeout: 30m



spring:
  application:
    name: CoffeeApp-Miahkykh
  datasource:
    url: jdbc:mysql://slj.demodev.cc/slj_kinocms?createDatabaseIfNotExist=true
    username: slj_kinocms
    password: "UC7w3mEt57"
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB


logging:
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"

  file:
    name: "/home/slj/projects/CoffeeApp-R.Miahkykh/logs/coffee_app.log"

  level:
    file: "INFO"


