

server:
  servlet:
    context-path: /admin-coffee-store

spring:
  application:
    name: CoffeeApp-Miahkykh
  datasource:
    url: jdbc:mysql://coffeeapp-miahkykh-mysql:3306/CoffeeAppMiahkykh?createDatabaseIfNotExist=true
    username: root
    password: "0000"
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB

upload:
  folder:
    path: "/home/slj/projects/CoffeeApp-R.Miahkykh/uploads"

logging:
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"

  file:
    name: "/home/slj/projects/CoffeeApp-R.Miahkykh/logs/coffeeappDocker.log"

  level:
    file: "INFO"


