server:
  servlet:
    session:
      timeout: 30m


spring:

  application:
    name: CoffeeApp
  datasource:
    url: jdbc:mysql://localhost:3306/CoffeeApp?createDatabaseIfNotExist=true
    username: root
    password: "0000"
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB

upload:
  folder:
    path: "C:\\Users\\Belwerk\\Downloads\\ProjectFiles\\CoffeeApp-R.Miahkykh\\uploads"

logging:
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"

  file:
    name: "C:\\Users\\Belwerk\\Downloads\\ProjectFiles\\CoffeeApp-R.Miahkykh\\logs\\CoffeeApp.log"

  level:
    file: "INFO"


application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 604800000 # 7 days
