name: Build and push coffeeapp image and restart containers

on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build app with Maven
        run: |
          mvn clean package -DskipTests=true


      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push coffeeapp image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/coffeeapp-miahkykh:latest

#      - name: Restart MySQL container
#        uses: appleboy/ssh-action@v1.0.3
#        with:
#          host: ${{ secrets.SSH_HOST }}
#          username: ${{ secrets.SSH_USERNAME }}
#          password: ${{ secrets.SSH_PASSWORD }}
#          script: |
#            echo "Restarting MySQL container"
#            docker stop coffeeapp-miahkykh-mysql || true
#            docker rm coffeeapp-miahkykh-mysql || true
#            docker run -d \
#              --name coffeeapp-miahkykh-mysql \
#              -e MYSQL_ROOT_PASSWORD=0000 \
#              -e MYSQL_DATABASE=CoffeeAppMiahkykh \
#              -p 3310:3306 \
#              mysql:latest
#            echo "MySQL container has been updated"

      - name: Restart coffeeapp container
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            echo "Restarting coffeeapp container"
            docker stop coffeeapp-miahkykh || true
            docker rm coffeeapp-miahkykh || true
            docker run -d \
              --name coffeeapp-miahkykh \
              -p 7649:8080 \
              --net coffeestore-miahkykh \
              -e SPRING_DATASOURCE_URL=jdbc:mysql://coffeeapp-miahkykh-mysql:3306/CoffeeAppMiahkykh?createDatabaseIfNotExist=true \
              -e SPRING_DATASOURCE_USERNAME=root \
              -e SPRING_DATASOURCE_PASSWORD=0000 \
              ${{ secrets.DOCKER_USERNAME }}/coffeeapp-miahkykh:latest
            echo "coffeeapp container has been updated"
            exit
