name: Build and push coffeeapp image and restart containers

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build app with Maven
        run: |
          mvn clean package -DskipTests=true

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.9.0

      - name: Build and push coffeeapp image
        uses: docker/build-push-action@v6.14.0
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/coffeeapp-miahkykh:latest

      - name: Debug SSH connection
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            echo "Testing SSH connection"
            date
            whoami
            uname -a
            df -h

      - name: SSH Restart MySQL container
        uses: cross-the-world/ssh-scp-ssh-pipelines@v1.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          user: ${{ secrets.SSH_USERNAME }}
          pass: ${{ secrets.SSH_PASSWORD }}
          first_ssh: |
            docker network ls | grep coffeestore-miahkykh || docker network create coffeestore-miahkykh
            ECHO Restarting MySQL container
            docker stop coffeeapp-miahkykh-mysql 2>/dev/null
            docker rm coffeeapp-miahkykh-mysql 2>/dev/null
            docker pull mysql:latest
            docker run -d --name coffeeapp-miahkykh-mysql --net coffeestore-miahkykh -e MYSQL_ROOT_PASSWORD=0000 -e MYSQL_DATABASE=CoffeeAppMiahkykh -p 3310:3306 mysql:latest
            ECHO MySQL container has been updated
          last_ssh: ECHO Finished restarting MySQL container

      - name: SSH Restart coffeeapp container
        uses: cross-the-world/ssh-scp-ssh-pipelines@v1.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          user: ${{ secrets.SSH_USERNAME }}
          pass: ${{ secrets.SSH_PASSWORD }}
          first_ssh: |
            docker network ls | grep coffeestore-miahkykh || docker network create coffeestore-miahkykh
            ECHO Restarting coffeeapp container
            docker stop coffeeapp-miahkykh 2>/dev/null
            docker rm coffeeapp-miahkykh 2>/dev/null
            docker pull glyuchnoglaz21/coffeeapp-miahkykh:latest
            docker run -d --name coffeeapp-miahkykh --net coffeestore-miahkykh -p 8080:8080 -e SPRING_DATASOURCE_URL=jdbc:mysql://coffeeapp-miahkykh-mysql:3306/CoffeeAppMiahkykh?createDatabaseIfNotExist=true -e SPRING_DATASOURCE_USERNAME=root -e SPRING_DATASOURCE_PASSWORD=0000 glyuchnoglaz21/coffeeapp-miahkykh:latest
            ECHO coffeeapp container has been updated
          last_ssh: ECHO Finished restarting coffeeapp container

