name: Java CI/CD Pipeline with Docker

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build app with Maven
        run: |
          mvn clean package -DskipTests=true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/coffeeapp-miahkykh:latest

      - name: Remove old container (if exists)
        run: |
          docker ps -a --format '{{.Names}}' | grep -q '^coffeeapp$' && \
          docker stop coffeeapp && \
          docker rm coffeeapp || echo "No existing container to remove."

      - name: Run new Docker container
        run: |
          docker run -d --name coffeeapp \
            -p 8080:8080 \
            -e SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/CoffeeAppMiahkykh?createDatabaseIfNotExist=true \
            -e SPRING_DATASOURCE_USERNAME=root \
            -e SPRING_DATASOURCE_PASSWORD=0000 \
            ${{ secrets.DOCKER_USERNAME }}/coffeeapp-miahkykh:latest
